# Generated by Django 3.2.8 on 2021-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=40)),
                ('Open', models.FloatField()),
                ('Close', models.FloatField()),
                ('Low', models.FloatField()),
                ('High', models.FloatField()),
                ('Change', models.FloatField()),
                ('Volume', models.FloatField()),
            ],
        ),
    ]
