# Generated by Django 3.2.8 on 2021-10-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_finance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosdaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.IntegerField()),
                ('Market', models.TextField()),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.IntegerField()),
                ('Market', models.TextField()),
                ('Name', models.TextField()),
            ],
        ),
    ]
